### ISSUE TITLE
Rewrite this lib on top of whitequark/ast

### ISSUE THREAD

**Issue by mbj** [mbj/axiom-sexp#2]
@dkubb You also feel this step would help us? We can feed that stuff into a mutant plugin, because it is API compatible!

**Comment by dkubb** [comment]
@mbj I'm not sure, maybe it would help. I suppose if the AST is the same we can share some code between them. I don't know if it means the same thing to mutate an axiom AST as a ruby AST, but it's nice to have a similar foundation amongst our gems.. it makes it easier to contribute too.
